### ISSUE TITLE
Bug: Cannot create volume snapshots if you fail to provide parameters on the volume snapshot class.

### ISSUE THREAD

**Issue by hughdanliu** [kubernetes-sigs/aws-fsx-openzfs-csi-driver#27]
/kind bug

**What happened?**
I attempted to create a new volume snapshot without specifying any parameters on the volume snapshot class. Instead, the creation is left hanging and the csi-controller is stuck in a CrashLoopBackOff sequence.

**What you expected to happen?**
The Volume Snapshot and associated FSx for OpenZFS snapshot should have created successfully

**How to reproduce it (as minimally and precisely as possible)?**
1. Apply a volume snapshot class without any parameters configured.
2. Attempt to create a new volume snapshot specifying that volume snapshot class.

**Anything else we need to know?**:
This will be fixed ASAP.

**Environment**
- Kubernetes version (use `kubectl version`): 1.25
- Driver version: v0.1.0

**Comment by gomesjason** [comment]
I'll be including this fix in my next PR

**Comment by hughdanliu** [comment]
Fix is merged. Waiting until next release before closing out this issue.

**Comment by jacobwolfaws** [comment]
A new image has been released, closing.
/close
