### ISSUE TITLE
Adopt Kubernetes recommended label for `app`

### ISSUE THREAD

**Issue by thetric** [kubernetes-sigs/aws-fsx-openzfs-csi-driver#28]
/kind bug

**What happened?**
The Helm chart is deployed with the resources labelled with `app` instead of the [Kubernetes recommended label](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) `app.kubernetes.io/name`.

**What you expected to happen?**

The Helm chart makes use of the recommended label.

**How to reproduce it (as minimally and precisely as possible)?**

Deploy it.

**Anything else we need to know?**:

This may possibly be a breaking change as it might require a re-installation of the Helm chart because the `selector` `matchLabels` will change.

Same issue in the AWS EBS CSI driver: https://github.com/kubernetes-csi/external-snapshotter/issues/843

**Environment**
- Kubernetes version (use `kubectl version`): 1.27
- Driver version: 0.1.0

**Please also attach debug logs to help us better diagnose**

n/a

**Comment by hughdanliu** [comment]
Thank you for bringing this to our attention. We will make this fix promptly.

**Comment by jacobwolfaws** [comment]
these changes have been released, closing. Thank you for opening this issue!
/close
