### ISSUE TITLE
v1.1.0 not released in Helm repository

### ISSUE THREAD

**Issue by yamadayutaka** [kubernetes-sigs/aws-fsx-openzfs-csi-driver#53]
**What happened?**

v1.1.0 not released in Helm repository.

**What you expected to happen?**

v1.1.0 can be installed from the Helm repository.

**How to reproduce it (as minimally and precisely as possible)?**

By executing the command below, you can confirm that v1.1.0 has not been released.

```
helm repo add aws-fsx-openzfs-csi-driver https://kubernetes-sigs.github.io/aws-fsx-openzfs-csi-driver
helm repo update
helm search repo aws-fsx-openzfs-csi-driver --versions
```

**Comment by jacobwolfaws** [comment]
Hi @yamadayutaka thank you for bringing this to our attention. The release workflow didn't update the gh-pages branch, which in turn prevented the release of the new helm version. This problem has been resolved and I've confirmed that the commands you're running work.
> helm search repo aws-fsx-openzfs-csi-driver --versions
NAME                                              	CHART VERSION	APP VERSION	DESCRIPTION
aws-fsx-openzfs-csi-driver/aws-fsx-openzfs-csi-...	1.1.0        	1.1.0      	A Helm chart for the AWS FSx for OpenZFS CSI Dr...
aws-fsx-openzfs-csi-driver/aws-fsx-openzfs-csi-...	1.0.0        	1.0.0      	A Helm chart for the AWS FSx for OpenZFS CSI Dr...
aws-fsx-openzfs-csi-driver/aws-fsx-openzfs-csi-...	0.1.0        	0.1.0      	A Helm chart for the AWS FSx for OpenZFS CSI Dr...

Please let us know if you encounter any more issues and feel free to reopen this issue if you're still having problems, closing this issue as it appears to be mitigated
/close

**Comment by yamadayutaka** [comment]
Hi @jacobwolfaws, Thank you for resolving this issue!
